// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgXEyOrSuaiZo1TCSV4NiwKg3KA9dMNo',
    appId: '1:956331379494:android:44129f6020c2baa9b48fe7',
    messagingSenderId: '956331379494',
    projectId: 't-ecommerce-app-adf1d',
    storageBucket: 't-ecommerce-app-adf1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_pGimVIu0Q8pFTFf2QTufNM-7N-4flE',
    appId: '1:956331379494:ios:e7ab9e5f81b692b4b48fe7',
    messagingSenderId: '956331379494',
    projectId: 't-ecommerce-app-adf1d',
    storageBucket: 't-ecommerce-app-adf1d.firebasestorage.app',
    iosClientId: '956331379494-t2dj8bgrnvvfgravg3ta1ksjsfpmo1m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapp',
  );

}